version = 0.1
[default.deploy.parameters]
stack_name = "ai-orchestration"
resolve_s3 = true
s3_prefix = "ai-orchestration"
region = "us-east-1"
profile = "sam-deploy"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
